service: quote-botler # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

custom:
  stage: ${opt:stage, self:provider.stage}
  # Fallback to default if it is not in prod.
  environment: ${file(./env.yml):${self:provider.stage}, file(./env.yml):default}

functions:
  hello:
    handler: handler.hello