service: quote-botler

provider:
  name: aws
  runtime: ruby2.5
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  memorySize: 256
  reservedConcurrency: 5
  timeout: 120
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/credential-store"
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: "arn:aws:kms:ap-southeast-1:*:key/d85c3293-cda4-4c24-8184-dfd9a9a46adf"
    - Effect: Allow
      Action:
        - comprehend:BatchDetectSentiment
      Resource: "*"

package:
  exclude:
    - .env
    - package*.json
    - node_modules
    - .pryrc
    - Rakefile
    - Dockerfile

functions:
  daily_quote:
    handler: routines/daily_quote.perform
    events:
      - schedule: cron(30 10 ? * 2-6 *)
        description: Tweet inspirational quotes daily on weekdays @ 630pm

  send_love:
    handler: routines/send_love.perform
    events:
      - schedule: cron(0 23 ? * 4 *)
        description: Tweet love to friends every thursday @ 7am
